# params.yaml
acoustics:
  max_formant_female: 5000    
  max_formant_male: 4500      
  n_formants: 5               
  long_vowel_threshold_ms: 80 
  f0_time_step: 0.01          
  scg_power: 2.0          

whisper:
  model_id: "openai/whisper-medium"  # 1024 demensions
  target_layers: [4, 20]             
  sampling_rate: 16000 

xlsr:
  model_id: "facebook/wav2vec2-large-xlsr-53"
  target_layers: [3, 9, 18]          
  sampling_rate: 16000 

normalisation:
  pca_dim_viz: 2       # for visualization
  pca_dim_cluster: 50  # for clustering             