[workspace]
name = "m1_stat final_phonetics_project"
version = "0.1.0"
description = "Acoustic and Neural Representations in a Phonetically Aligned Speech Corpus"
channels = ["conda-forge", "pytorch"]
platforms = ["win-64"]

[dependencies]
python = ">=3.10"
pandas = "*"
numpy = "*"

# phonetical analysis
librosa = "*"

# statistical analysis and machine learning
pytorch = "*"
transformers = "*"
scikit-learn = ">=1.8.0,<2"
statsmodels = "*"
scipy = "*"

# visualization
matplotlib = "*"
seaborn = "*"

dvc = "*"
pyyaml = ">=6.0.3,<7"
umap-learn = ">=0.5.12,<0.6"

[pypi-dependencies]
praat-parselmouth = "*"
tgt = ">=1.5, <2"
soundfile = "*"

[tasks]
parse = "python scripts/01_parse_corpus.py"
extract_acoustics = "python scripts/02_extract_acoustics.py"
extract_whisper = "python scripts/03_extract_whisper.py"
extract_xlsr = "python scripts/04_extract_xlsr.py"
normalize = "python scripts/05_normalise.py"

pipeline = "dvc repro"
